name: pull-request

on:
  pull_request:
    branches: [main]

jobs:
  Test-check:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test

  Build:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public/

  Deploy:
    if: ${{ always() }}
    runs-on: ubuntu-latest

    steps:
      - name: Ready
        run: echo "Done"
