name: pull-request

on:
  pull_request:
    branches: [main]

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test
