name: "Push to main"

on:
  push:
    branches: ["main"]

jobs:
  push-main:
    runs-on: ubuntu-latest

    env:
      NAME: Sarai_Rojas

    steps:
      - name: First
        id: step_1
        run: echo "MY_ACTION=Push to main" >> $GITHUB_OUTPUT
      - name: Second
        run: echo "You have $${{steps.step_1.outputs.MY_ACTION}} directly"
      - name: Third
        run: echo "By $NAME"

  Changes-already-in-main:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: push-main
    runs-on: ubuntu-latest
    steps:
      - name: Unique
        run: echo "Already in main"
      - name: content
        run: ls -al
      - name: Action
        uses: actions/checkout@v4
      - name: content
        run: ls -al
