name: "Push to main"

on:
  push:
    branches: ["main"]

jobs:
  push-main:
    runs-on: ubuntu-latest

    env:
      NAME: Sarai_Rojas

    steps:
      - name: First
        run: echo "Push to main"
      - name: Second
        run: echo "You are pushing to main directly"
      - name: Third
        run: echo "By $NAME"

  Changes-already-in-main:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: push-main
    runs-on: ubuntu-latest
    steps:
      - name: Unique
        run: echo "Already in main"
      - name: content
        run: ls -al
      - name: Action
        run: actions/checkout@v4
      - name: content
        run: ls -al
