name: "Push to main"

on:
  push:
    branches: ["main"]

jobs:
  push-main:
    runs-on: ubuntu-latest
    steps:
      - name: First
        run: echo "Push to main"
      - name: Second
        run: echo "You are pushing to main directly"
